### ISSUE TITLE
Low download and high upload speed issue

### ISSUE THREAD

**Issue by VNovytskyi** [ewpa/LibSSH-ESP32#13] opened 2021-11-05 20:53 UTC
When I receive a file from the Ubuntu SCP server to ESP32 the size of receive package is too small (only 72 Bytes). When I transmit a file from ESP32 to the Ubuntu SCP server the size of the transmitting package is 4096 Byte (as a buffer which I set). In source files, I read that a function ssh_channel_read_timeout may return fewer bytes of data. How I can speed up the download?
I use the code below to download file from the server:
```c
do {
      r = ssh_scp_read(src.scp, copy_buffer, SCP_CLIENT_TX_RX_BUFF);
      if (r == SSH_ERROR) { 
        LOG_E(TAG, "Error reading scp: %s\n", ssh_get_error(src.session));
        break;
      } else if (r == 0) {
        break;
      }

      w = dest.file.write(copy_buffer, r);
      if (w <= 0) {
        LOG_E(TAG, "Error writing in local file: %s\n", strerror(errno));
        break;
      }

      transferred_bytes_count += r;
} while (transferred_bytes_count < file_size);
```
And this one code to upload files to the server:
```c
do {
      int r = src.file.read(copy_buffer, SCP_CLIENT_TX_RX_BUFF);
      if (r == 0) {
        break;
      }

      if (r < 0) {
        LOG_E(TAG, "Error read file: r = %d\n", r);
        break;
      }

      if (ssh_scp_write(dest.scp, copy_buffer, r) == SSH_ERROR) {
        LOG_E(TAG, "Error writing in scp: %s\n", ssh_get_error(dest.session));
        break;
      }

      transferred_bytes_count += r;
      printf("%d\n", r);
} while (transferred_bytes_count < file_size);
```
Download result:
![1](https://user-images.githubusercontent.com/48761198/140578313-3495d84d-e243-4cca-b24d-5f291271d851.PNG)

Upload result:
![Upload log](https://user-images.githubusercontent.com/48761198/140578327-f8e632ff-3440-4a9c-ad41-d1007646d232.PNG)

**Comment by ewpa** [comment] 2021-11-07 09:51
As part of the porting process I reduce many windows and buffers.  The goal is to improve stability -- with stability being prioritised over performance.  Please could you enable verbose mode and review the output as hopefully this will provide further insight.  An example of how to achieve this is in example `libssh_scp.ino`, variable `verbosity` to at least 2:
```
static int verbosity = 2;
...
ssh_options_set(session, SSH_OPTIONS_LOG_VERBOSITY, &verbosity);
```
This should help find the limitation, e.g.
```
[1970/01/01 00:00:43.024618, 2] grow_window:  growing window (channel 43:0) to 72 bytes : not needed (72 bytes)
```
So it certainly seems to be attempting a window increase and being limited at 72 bytes.

**Comment by ewpa** [comment] 2021-11-07 10:33
On line 3737 of `src/channels.c` please change `WINDOWBASE` to `WINDOWBEGIN`.  Let me know if this fixes this for you and I will push the fix.

**Comment by ewpa** [comment] 2021-11-08 12:44
You found I gave the wrong line number.  Please change that line to the following.
```
uint32_t new_window = minimumsize > WINDOWBEGIN ? minimumsize : WINDOWBEGIN;
```
I have some regression tests to perform before I can release the code change.

**Comment by ewpa** [comment] 2021-11-08 16:11
Feel free to close the issue now.

**Closed** 2021-11-08 16:30 UTC
Labels: bug
